package by.epam.module04.task4105;

public enum Food {
    ROOM_ONLY,
    BED_ANG_BREAKFAST,
    HALF_BOARD,
    HALF_BOARD_PLUS,
    HALF_BOARD_SUPERIOR,
    FULL_BOARD,
    FULL_BOARD_PLUS,
    ALL_INCLUSIVE,
    ULTRA_ALL_INCLUSIVE,
    HIGH_CLASS_ALL_INCLUSIVE,
    CONTINENTAL_BREAKFAST,
    AMERICAN_BREAKFAST,
    ENGLISH_BREAKFAST
}
