package by.epam.module04.task4105;

public enum VoucherType {
    REST,
    ENTERTAINMENT,
    EXCURSION,
    TREATMENT,
    SHOPPING,
    CRUISE,
    SKI,
    DIVING,
    SAFARI_HUNTING_FISHING,
    SPORT_HIKING_EXTREME,
    INDIVIDUAL_AND_EXOTIC,
    WEDDING,
    FOR_TRAINING,
    FESTIVALS_COMPETITIONS_TOURNAMENTS,
    PILGRIMAGE
}
